### PR TITLE
add a d.ts

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Figured this would just be a nice thing to do :)

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Thanks! Does package.json#files need to be updated?

**Comment by JustinBeckwith** [comment]
Np!  I don't believe it does.  If "files" isn't defined, I think it defaults to packaging the entire directory, and uses .npmignore to blacklist. I tried 'npm pack' and it seemed it work :)

**Comment by stephenplusplus** [comment]
Oh woops, I'll have to add one of those! Thanks for this change!

**Comment by JustinBeckwith** [comment]
Rad.  Mind pushing a release?

**Comment by stephenplusplus** [comment]
I'll shoot for tomorrow morning!

**Pull request merged**
